name: gibireplikleri
description: Gibi dizisinin repliklerini dinleyip, arkadaşlarınızla paylaşabilirsiniz!

publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  google_mobile_ads: ^2.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  provider: ^6.0.5
  share_plus: ^6.3.2
  url_launcher: ^6.1.10
  audioplayers: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/sounds/
    - assets/texts/


  fonts:
    - family: Euclid
      fonts:
        - asset: assets\fonts\Euclid Circular B Bold Italic.ttf
          weight: 700
        - asset: assets\fonts\Euclid Circular B Bold.ttf
          weight: 700
        - asset: assets\fonts\Euclid Circular B Italic.ttf
        - asset: assets\fonts\Euclid Circular B Light Italic.ttf
        - asset: assets\fonts\Euclid Circular B Light.ttf
          weight: 200
        - asset: assets\fonts\Euclid Circular B Medium Italic.ttf
        - asset: assets\fonts\Euclid Circular B Medium.ttf
          weight: 500
        - asset: assets\fonts\Euclid Circular B Regular.ttf
          weight: 400
        - asset: assets\fonts\Euclid Circular B SemiBold Italic.ttf
        - asset: assets\fonts\Euclid Circular B SemiBold.ttf
          weight: 600    
    - family: GibiIcons
      fonts:
        - asset: assets\icons\GibiIcons.ttf

